### PR TITLE
Update parameter type definitions

### PR DESCRIPTION
**Pull request by merckxite**

### CODE REVIEW

**Comment by merckxite** [comment]
@Flash3001 I think my issue may be merely symptomatic, it appears that wherever context is referenced as a parameter, it is passed as an NSObject rather than CGContext (from what I've seen). Have noticed the same of indices, and there may be others. It shouldn't be hard to go through and do a find/replace on all those instances so we can cover off most cases, so I will do that and add it to this PR before we close it.

**Comment by merckxite** [comment]
@Flash3001 I've made the changed I talked about in the previous comment, this PR is ready to be merged when you're ready

**Comment by Flash3001** [comment]
@merckxite Thank you for the reminder and I'm sorry for the long delay.

Thank you for the work =) 

If you find any other places with issues in the ApiDefinition, please fell free to send more PR. It helps a lot. The API is huge and I don't know all of it, some changes are mechanic so it is easy to miss something.

**Comment by Flash3001** [comment]
Just pushed the new Nuget package =)

**Pull request merged**
